# Common.
baseURL: "https://mxs.sbrk.org/"
title: "Yet Another Bunch of Bytes"
languageCode: "en-us"
contentdir: "content"
publishdir: "public"

# Menu.
sectionPagesMenu: "navigation"
titleCaseStyle: "Chicago"

# Allow HTML within markdown.
markup:
  goldmark:
    renderer:
      unsafe: true
