# Common.
baseURL: "https://mxs.sbrk.org/"
title: "Yet Another Bunch of Bytes"
languageCode: "en-us"
contentdir: "content"
publishdir: "public"

# Menu.
sectionPagesMenu: "navigation"
titleCaseStyle: "Chicago"
menu:
  main:
  - identifier: home
    name: home
    url: /
    weight: -1
  - identifier: photography
    name: photo
    url: /photography/
    weight: 1
  - identifier: writings
    name: writings
    url: /writings/
    weight: 2
  - identifier: code
    name: code
    url: /code/
    weight: 3
  - identifier: projects
    name: projects
    url: /projects/
    weight: 4
  - identifier: music
    name: music
    url: /music/
    weight: 5
  - identifier: about
    name: about
    url: /about/
    weight: 6

# Allow HTML within markdown.
markup:
  goldmark:
    renderer:
      unsafe: true
