# Common.
baseURL: "https://mxs.sbrk.org/"
title: "Yet Another Bunch of Bytes"
languageCode: "en-us"
contentdir: "content"
publishdir: "public"
uglyURLs: true

# Menu.
sectionPagesMenu: "navigation"
titleCaseStyle: "Chicago"
menu:
  main:
  - identifier: home
    name: "&#xe800;"
    url: /home.html
    weight: -1
  - identifier: photography
    name: "&#xe801;"
    url: /photography.html
    weight: 1
  - identifier: writings
    name: "&#xe802;"
    url: /writings.html
    weight: 2
  - identifier: code
    name: "&#xf121;"
    url: /code.html
    weight: 3
  - identifier: projects
    name: "&#xe803;"
    url: /projects.html
    weight: 4
  - identifier: music
    name: "&#xe804;"
    url: /music.html
    weight: 5
  - identifier: about
    name: "&#xe805;"
    url: /about.html
    weight: 6

# Allow HTML within markdown.
markup:
  goldmark:
    renderer:
      unsafe: true
